"""Add resume and cover letter foreign keys to candidatures

Revision ID: 0688e5cf39d3
Revises: 1cdd29ac919d
Create Date: 2026-10-08 19:15:05.961602

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0688e5cf39d3'
down_revision: Union[str, None] = '1cdd29ac919d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidatures', sa.Column('resume_id', sa.String(length=36), nullable=True))
    op.add_column('candidatures', sa.Column('cover_letter_id', sa.String(length=36), nullable=True))
    op.create_foreign_key('fk_candidatures_cover_letter_id', 'candidatures', 'resumes', ['cover_letter_id'], ['id'], ondelete='SET NULL')
    op.create_foreign_key('fk_candidatures_resume_id', 'candidatures', 'resumes', ['resume_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_candidatures_cover_letter_id', 'candidatures', type_='foreignkey')
    op.drop_constraint('fk_candidatures_resume_id', 'candidatures', type_='foreignkey')
    op.drop_column('candidatures', 'cover_letter_id')
    op.drop_column('candidatures', 'resume_id')
    # ### end Alembic commands ###
