"""Add match_score and job_description to candidatures

Revision ID: 1cdd29ac919d
Revises: 2b21b242b76c
Create Date: 2026-10-08 18:56:48.977279

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1cdd29ac919d'
down_revision: Union[str, None] = '2b21b242b76c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidatures', sa.Column('match_score', sa.Integer(), nullable=True))
    op.add_column('candidatures', sa.Column('job_description', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('candidatures', 'job_description')
    op.drop_column('candidatures', 'match_score')
    # ### end Alembic commands ###
