"""initial_schema

Revision ID: 56fb8f7e1806
Revises: 
Create Date: 2026-10-01 12:41:14.851648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '56fb8f7e1806'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('code', table_name='subscription_plans')
    op.drop_table('subscription_plans')
    op.create_foreign_key(None, 'achievements', 'master_profiles', ['profile_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'audit_logs', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'candidatures', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'certifications', 'master_profiles', ['profile_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'custom_section_items', 'custom_sections', ['section_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'custom_sections', 'master_profiles', ['profile_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'documents', 'master_profiles', ['profile_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'educations', 'master_profiles', ['profile_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'experiences', 'master_profiles', ['profile_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'exports', 'resumes', ['resume_id'], ['id'])
    op.create_foreign_key(None, 'languages', 'master_profiles', ['profile_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'links', 'master_profiles', ['profile_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'master_profiles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'payments', 'templates', ['template_id'], ['id'])
    op.create_foreign_key(None, 'payments', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'payments', 'resumes', ['resume_id'], ['id'])
    op.create_foreign_key(None, 'projects', 'master_profiles', ['profile_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'public_pages', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'resumes', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'resumes', 'templates', ['template_id'], ['id'])
    op.create_foreign_key(None, 'skills', 'master_profiles', ['profile_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'template_assets', 'templates', ['template_id'], ['id'])
    op.create_foreign_key(None, 'templates', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'user_template_access', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'user_template_access', 'templates', ['template_id'], ['id'])
    op.create_foreign_key(None, 'user_template_access', 'payments', ['payment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_template_access', type_='foreignkey')
    op.drop_constraint(None, 'user_template_access', type_='foreignkey')
    op.drop_constraint(None, 'user_template_access', type_='foreignkey')
    op.drop_constraint(None, 'templates', type_='foreignkey')
    op.drop_constraint(None, 'template_assets', type_='foreignkey')
    op.drop_constraint(None, 'skills', type_='foreignkey')
    op.drop_constraint(None, 'resumes', type_='foreignkey')
    op.drop_constraint(None, 'resumes', type_='foreignkey')
    op.drop_constraint(None, 'public_pages', type_='foreignkey')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_constraint(None, 'master_profiles', type_='foreignkey')
    op.drop_constraint(None, 'links', type_='foreignkey')
    op.drop_constraint(None, 'languages', type_='foreignkey')
    op.drop_constraint(None, 'exports', type_='foreignkey')
    op.drop_constraint(None, 'experiences', type_='foreignkey')
    op.drop_constraint(None, 'educations', type_='foreignkey')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_constraint(None, 'custom_sections', type_='foreignkey')
    op.drop_constraint(None, 'custom_section_items', type_='foreignkey')
    op.drop_constraint(None, 'certifications', type_='foreignkey')
    op.drop_constraint(None, 'candidatures', type_='foreignkey')
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.drop_constraint(None, 'achievements', type_='foreignkey')
    op.create_table('subscription_plans',
    sa.Column('id', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=36), nullable=False),
    sa.Column('name', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=100), nullable=False),
    sa.Column('code', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=50), nullable=False),
    sa.Column('price', mysql.DECIMAL(precision=10, scale=2), nullable=False),
    sa.Column('currency', mysql.VARCHAR(collation='utf8mb4_unicode_ci', length=10), server_default=sa.text("'XOF'"), nullable=True),
    sa.Column('duration_days', mysql.INTEGER(), server_default=sa.text("'0'"), autoincrement=False, nullable=True),
    sa.Column('features', mysql.JSON(), nullable=True),
    sa.Column('is_active', mysql.TINYINT(display_width=1), server_default=sa.text("'1'"), autoincrement=False, nullable=True),
    sa.Column('created_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=True),
    sa.Column('updated_at', mysql.DATETIME(), server_default=sa.text('CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    mysql_collate='utf8mb4_unicode_ci',
    mysql_default_charset='utf8mb4',
    mysql_engine='MyISAM'
    )
    op.create_index('code', 'subscription_plans', ['code'], unique=True)
    # ### end Alembic commands ###
