"""add token_version to users

Revision ID: 8caa5e4172bc
Revises: c1f9a3d72e80
Create Date: 2026-10-08 16:35:06.544670

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '8caa5e4172bc'
down_revision: Union[str, None] = 'c1f9a3d72e80'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_achievements_profile_id'), 'achievements', ['profile_id'], unique=False)
    op.create_foreign_key(None, 'achievements', 'master_profiles', ['profile_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'audit_logs', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'candidatures', 'users', ['user_id'], ['id'])
    op.create_index(op.f('ix_certifications_profile_id'), 'certifications', ['profile_id'], unique=False)
    op.create_foreign_key(None, 'certifications', 'master_profiles', ['profile_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_custom_section_items_section_id'), 'custom_section_items', ['section_id'], unique=False)
    op.create_foreign_key(None, 'custom_section_items', 'custom_sections', ['section_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_custom_sections_profile_id'), 'custom_sections', ['profile_id'], unique=False)
    op.create_foreign_key(None, 'custom_sections', 'master_profiles', ['profile_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_documents_profile_id'), 'documents', ['profile_id'], unique=False)
    op.create_foreign_key(None, 'documents', 'master_profiles', ['profile_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_educations_profile_id'), 'educations', ['profile_id'], unique=False)
    op.create_foreign_key(None, 'educations', 'master_profiles', ['profile_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_experiences_profile_id'), 'experiences', ['profile_id'], unique=False)
    op.create_foreign_key(None, 'experiences', 'master_profiles', ['profile_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'exports', 'resumes', ['resume_id'], ['id'])
    op.create_index(op.f('ix_languages_profile_id'), 'languages', ['profile_id'], unique=False)
    op.create_foreign_key(None, 'languages', 'master_profiles', ['profile_id'], ['id'], ondelete='CASCADE')
    op.create_index(op.f('ix_links_profile_id'), 'links', ['profile_id'], unique=False)
    op.create_foreign_key(None, 'links', 'master_profiles', ['profile_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'master_profiles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'payments', 'templates', ['template_id'], ['id'])
    op.create_foreign_key(None, 'payments', 'resumes', ['resume_id'], ['id'])
    op.create_foreign_key(None, 'payments', 'users', ['user_id'], ['id'])
    op.create_index(op.f('ix_projects_profile_id'), 'projects', ['profile_id'], unique=False)
    op.create_foreign_key(None, 'projects', 'master_profiles', ['profile_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'public_pages', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'resumes', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'resumes', 'templates', ['template_id'], ['id'])
    op.create_index(op.f('ix_skills_profile_id'), 'skills', ['profile_id'], unique=False)
    op.create_foreign_key(None, 'skills', 'master_profiles', ['profile_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'template_assets', 'templates', ['template_id'], ['id'])
    op.create_foreign_key(None, 'templates', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'user_template_access', 'payments', ['payment_id'], ['id'])
    op.create_foreign_key(None, 'user_template_access', 'templates', ['template_id'], ['id'])
    op.create_foreign_key(None, 'user_template_access', 'users', ['user_id'], ['id'])
    op.add_column('users', sa.Column('token_version', sa.Integer(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'token_version')
    op.drop_constraint(None, 'user_template_access', type_='foreignkey')
    op.drop_constraint(None, 'user_template_access', type_='foreignkey')
    op.drop_constraint(None, 'user_template_access', type_='foreignkey')
    op.drop_constraint(None, 'templates', type_='foreignkey')
    op.drop_constraint(None, 'template_assets', type_='foreignkey')
    op.drop_constraint(None, 'skills', type_='foreignkey')
    op.drop_index(op.f('ix_skills_profile_id'), table_name='skills')
    op.drop_constraint(None, 'resumes', type_='foreignkey')
    op.drop_constraint(None, 'resumes', type_='foreignkey')
    op.drop_constraint(None, 'public_pages', type_='foreignkey')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_index(op.f('ix_projects_profile_id'), table_name='projects')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_constraint(None, 'master_profiles', type_='foreignkey')
    op.drop_constraint(None, 'links', type_='foreignkey')
    op.drop_index(op.f('ix_links_profile_id'), table_name='links')
    op.drop_constraint(None, 'languages', type_='foreignkey')
    op.drop_index(op.f('ix_languages_profile_id'), table_name='languages')
    op.drop_constraint(None, 'exports', type_='foreignkey')
    op.drop_constraint(None, 'experiences', type_='foreignkey')
    op.drop_index(op.f('ix_experiences_profile_id'), table_name='experiences')
    op.drop_constraint(None, 'educations', type_='foreignkey')
    op.drop_index(op.f('ix_educations_profile_id'), table_name='educations')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_index(op.f('ix_documents_profile_id'), table_name='documents')
    op.drop_constraint(None, 'custom_sections', type_='foreignkey')
    op.drop_index(op.f('ix_custom_sections_profile_id'), table_name='custom_sections')
    op.drop_constraint(None, 'custom_section_items', type_='foreignkey')
    op.drop_index(op.f('ix_custom_section_items_section_id'), table_name='custom_section_items')
    op.drop_constraint(None, 'certifications', type_='foreignkey')
    op.drop_index(op.f('ix_certifications_profile_id'), table_name='certifications')
    op.drop_constraint(None, 'candidatures', type_='foreignkey')
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.drop_constraint(None, 'achievements', type_='foreignkey')
    op.drop_index(op.f('ix_achievements_profile_id'), table_name='achievements')
    # ### end Alembic commands ###
