"""Add marital_status to profile

Revision ID: 950e26710ac5
Revises: 56fb8f7e1806
Create Date: 2026-10-01 13:05:49.254879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '950e26710ac5'
down_revision: Union[str, None] = '56fb8f7e1806'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('subscription_plans',
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('price', sa.Numeric(precision=10, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=10), nullable=True),
    sa.Column('duration_days', sa.Integer(), nullable=True),
    sa.Column('features', sa.JSON(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('code')
    )
    op.create_foreign_key(None, 'achievements', 'master_profiles', ['profile_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'audit_logs', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'candidatures', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'certifications', 'master_profiles', ['profile_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'custom_section_items', 'custom_sections', ['section_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'custom_sections', 'master_profiles', ['profile_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'documents', 'master_profiles', ['profile_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'educations', 'master_profiles', ['profile_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'experiences', 'master_profiles', ['profile_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'exports', 'resumes', ['resume_id'], ['id'])
    op.create_foreign_key(None, 'languages', 'master_profiles', ['profile_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'links', 'master_profiles', ['profile_id'], ['id'], ondelete='CASCADE')
    op.add_column('master_profiles', sa.Column('marital_status', sa.String(length=100), nullable=True))
    op.create_foreign_key(None, 'master_profiles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'payments', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'payments', 'templates', ['template_id'], ['id'])
    op.create_foreign_key(None, 'payments', 'resumes', ['resume_id'], ['id'])
    op.create_foreign_key(None, 'projects', 'master_profiles', ['profile_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'public_pages', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'resumes', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'resumes', 'templates', ['template_id'], ['id'])
    op.create_foreign_key(None, 'skills', 'master_profiles', ['profile_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'template_assets', 'templates', ['template_id'], ['id'])
    op.create_foreign_key(None, 'templates', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'user_template_access', 'templates', ['template_id'], ['id'])
    op.create_foreign_key(None, 'user_template_access', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'user_template_access', 'payments', ['payment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_template_access', type_='foreignkey')
    op.drop_constraint(None, 'user_template_access', type_='foreignkey')
    op.drop_constraint(None, 'user_template_access', type_='foreignkey')
    op.drop_constraint(None, 'templates', type_='foreignkey')
    op.drop_constraint(None, 'template_assets', type_='foreignkey')
    op.drop_constraint(None, 'skills', type_='foreignkey')
    op.drop_constraint(None, 'resumes', type_='foreignkey')
    op.drop_constraint(None, 'resumes', type_='foreignkey')
    op.drop_constraint(None, 'public_pages', type_='foreignkey')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_constraint(None, 'master_profiles', type_='foreignkey')
    op.drop_column('master_profiles', 'marital_status')
    op.drop_constraint(None, 'links', type_='foreignkey')
    op.drop_constraint(None, 'languages', type_='foreignkey')
    op.drop_constraint(None, 'exports', type_='foreignkey')
    op.drop_constraint(None, 'experiences', type_='foreignkey')
    op.drop_constraint(None, 'educations', type_='foreignkey')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_constraint(None, 'custom_sections', type_='foreignkey')
    op.drop_constraint(None, 'custom_section_items', type_='foreignkey')
    op.drop_constraint(None, 'certifications', type_='foreignkey')
    op.drop_constraint(None, 'candidatures', type_='foreignkey')
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.drop_constraint(None, 'achievements', type_='foreignkey')
    op.drop_table('subscription_plans')
    # ### end Alembic commands ###
