"""add ai_logs table

Revision ID: bf0e0733bd6a
Revises: bd4c469e6c9b
Create Date: 2026-10-08 17:00:50.129089

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf0e0733bd6a'
down_revision: Union[str, None] = 'bd4c469e6c9b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'achievements', 'master_profiles', ['profile_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'ai_logs', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'audit_logs', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'candidatures', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'certifications', 'master_profiles', ['profile_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'custom_section_items', 'custom_sections', ['section_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'custom_sections', 'master_profiles', ['profile_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'documents', 'master_profiles', ['profile_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'educations', 'master_profiles', ['profile_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'experiences', 'master_profiles', ['profile_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'exports', 'resumes', ['resume_id'], ['id'])
    op.create_foreign_key(None, 'languages', 'master_profiles', ['profile_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'links', 'master_profiles', ['profile_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'master_profiles', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'payments', 'resumes', ['resume_id'], ['id'])
    op.create_foreign_key(None, 'payments', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'payments', 'templates', ['template_id'], ['id'])
    op.create_foreign_key(None, 'projects', 'master_profiles', ['profile_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'public_pages', 'users', ['user_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'resumes', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'resumes', 'templates', ['template_id'], ['id'])
    op.create_foreign_key(None, 'skills', 'master_profiles', ['profile_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'template_assets', 'templates', ['template_id'], ['id'])
    op.create_foreign_key(None, 'templates', 'users', ['created_by'], ['id'])
    op.create_foreign_key(None, 'user_template_access', 'users', ['user_id'], ['id'])
    op.create_foreign_key(None, 'user_template_access', 'templates', ['template_id'], ['id'])
    op.create_foreign_key(None, 'user_template_access', 'payments', ['payment_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'user_template_access', type_='foreignkey')
    op.drop_constraint(None, 'user_template_access', type_='foreignkey')
    op.drop_constraint(None, 'user_template_access', type_='foreignkey')
    op.drop_constraint(None, 'templates', type_='foreignkey')
    op.drop_constraint(None, 'template_assets', type_='foreignkey')
    op.drop_constraint(None, 'skills', type_='foreignkey')
    op.drop_constraint(None, 'resumes', type_='foreignkey')
    op.drop_constraint(None, 'resumes', type_='foreignkey')
    op.drop_constraint(None, 'public_pages', type_='foreignkey')
    op.drop_constraint(None, 'projects', type_='foreignkey')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_constraint(None, 'payments', type_='foreignkey')
    op.drop_constraint(None, 'master_profiles', type_='foreignkey')
    op.drop_constraint(None, 'links', type_='foreignkey')
    op.drop_constraint(None, 'languages', type_='foreignkey')
    op.drop_constraint(None, 'exports', type_='foreignkey')
    op.drop_constraint(None, 'experiences', type_='foreignkey')
    op.drop_constraint(None, 'educations', type_='foreignkey')
    op.drop_constraint(None, 'documents', type_='foreignkey')
    op.drop_constraint(None, 'custom_sections', type_='foreignkey')
    op.drop_constraint(None, 'custom_section_items', type_='foreignkey')
    op.drop_constraint(None, 'certifications', type_='foreignkey')
    op.drop_constraint(None, 'candidatures', type_='foreignkey')
    op.drop_constraint(None, 'audit_logs', type_='foreignkey')
    op.drop_constraint(None, 'ai_logs', type_='foreignkey')
    op.drop_constraint(None, 'achievements', type_='foreignkey')
    # ### end Alembic commands ###
