"""Add profile privacy fields

Revision ID: db9e4ae143bc
Revises: eec3e093c62c
Create Date: 2026-10-08 19:36:30.824483

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db9e4ae143bc'
down_revision: Union[str, None] = 'eec3e093c62c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('master_profiles', sa.Column('show_email', sa.Boolean(), nullable=True))
    op.add_column('master_profiles', sa.Column('show_phone', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###

def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('master_profiles', 'show_phone')
    op.drop_column('master_profiles', 'show_email')
    # ### end Alembic commands ###
